server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
        - id: simulator-service
          uri: lb://simulator-service
          predicates:
            - Path=/simulator/**
          filters:
            - StripPrefix=1
        - id: ingestion-service
          uri: lb://ingestion-service
          predicates:
            - Path=/ingest/**
          filters:
            - StripPrefix=1
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/billing/**
          filters:
            - StripPrefix=1
        - id: anomaly-service
          uri: lb://anomaly-service
          predicates:
            - Path=/anomaly/**
          filters:
            - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true