server:
  port: 8084
spring:
  application:
    name: anomaly-service
  datasource:
    url: jdbc:h2:mem:anomalydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
anomaly:
  threshold:
    high: 45.0
    medium: 14.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
