server:
  port: 8080
spring:
  application:
    name: api-gateway
  config:
    import: "configserver:http://localhost:8888"
jwt:
  secret: ecostream-secret-key-must-be-at-least-256-bits-long
management:
  endpoints:
    web:
      exposure:
        include: "*"
