server:
  port: 8080
spring:
  application:
    name: api-gateway
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
jwt:
  secret: ecostream-secret-key-must-be-at-least-256-bits-long
management:
  endpoints:
    web:
      exposure:
        include: "*"





